# This file runs every 6 hours and updates logs with ChatGPT
name: Update Dev Logs with ChatGPT

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Manual trigger

jobs:
  update-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Send prompt to ChatGPT
      run: |
        curl -X POST https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
          -d '{
               "model": "gpt-4",
               "messages": [{"role": "user", "content": "Write a developer progress log for Drawn-Together based on recent commits."}],
               "temperature": 0.7
             }' > gpt_response.json

    - name: Extract and save log text
      run: |
        jq -r '.choices[0].message.content' gpt_response.json > docs/logs.md

    - name: Commit and push logs
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update dev logs via ChatGPT"
        file_pattern: 'docs/logs.md'
        branch: main
