name: Update Dev Logs & Visuals

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Send prompt to ChatGPT
        run: |
          curl -X POST https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
                 "model": "gpt-4",
                 "messages": [{"role": "user", "content": "Write a developer progress log for Drawn-Together based on recent commits."}],
                 "temperature": 0.7
               }' > gpt_response.json

      - name: Extract and save log text
        run: |
          jq -r '.choices[0].message.content' gpt_response.json > docs/logs.md

      - name: Generate progress chart
        run: |
          curl "https://quickchart.io/chart" \
            -d '{
                  "width": 600,
                  "height": 300,
                  "format": "png",
                  "chart": {
                    "type": "bar",
                    "data": {
                      "labels": ["Movement","Combat","Multiplayer","UI","Art"],
                      "datasets": [{
                        "label": "Completion %",
                        "data": [40,25,15,10,5],
                        "backgroundColor": "rgba(0,255,204,0.6)"
                      }]
                    }
                  }
                }' \
            --output docs/assets/progress-chart.png

      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update dev logs & visuals via ChatGPT"
          file_pattern: 'docs/logs.md,docs/assets/progress-chart.png'
          branch: main
