name: Auto Dev Log Generator

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:        # Manual trigger
  push:                     # Also run when you push anything

jobs:
  log-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Dev Log from ChatGPT
        run: |
          curl -X POST https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
                 "model": "gpt-4",
                 "messages": [{"role": "user", "content": "Write a short dev log about the latest progress in a game called Drawn-Together."}],
                 "temperature": 0.7
               }' > gpt_response.json

      - name: Save Dev Log to logs.md
        run: |
          echo "# Developer Log" > logs.md
          echo "" >> logs.md
          jq -r '.choices[0].message.content' gpt_response.json >> logs.md

      - name: Commit and Push Log
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto: Update Dev Log"
          file_pattern: "logs.md"
